# Generated by Django 2.2.1 on 2019-09-12 04:33

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=500)),
                ('ishusban', models.BooleanField(default=1)),
                ('code', models.CharField(max_length=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Thông Tin',
            },
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=500)),
                ('decription', models.CharField(blank=True, max_length=200)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Tên Album',
            },
        ),
        migrations.CreateModel(
            name='Wedding_Invitation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feast', models.CharField(max_length=100)),
                ('time_calendar', models.DateField(verbose_name='date published')),
                ('time_lunar', models.DateField(verbose_name='date published')),
                ('location', models.CharField(max_length=500)),
                ('code', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='mystory.About')),
            ],
            options={
                'verbose_name_plural': 'Thiệp Cưới',
            },
        ),
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100)),
                ('slug', models.SlugField(max_length=200)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('images', models.ImageField(upload_to='story/%Y/%m/%d')),
                ('content', models.CharField(blank=True, max_length=5000)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Câu Chuyện Tình Yêu',
            },
        ),
        migrations.CreateModel(
            name='Invitee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(blank=True, max_length=13, validators=[django.core.validators.RegexValidator(message='Số điện thoại phải có định dạng 0xxxxxxxxxxx.', regex='^[0-9]{8,11}$')])),
                ('address', models.CharField(max_length=100)),
                ('ivitation', models.BooleanField(default=0)),
                ('adherence_wedding', models.BooleanField(default=0)),
                ('money_wedding', models.CharField(default=0, max_length=10)),
                ('guestof', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mystory.About')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Khách Mời',
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path_img', models.ImageField(blank=True, upload_to='gallery/%Y/%m/%d')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('decription', models.CharField(blank=True, max_length=50000)),
                ('gallery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mystory.Gallery')),
            ],
            options={
                'verbose_name_plural': 'Hình Ảnh',
            },
        ),
        migrations.CreateModel(
            name='Blessing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('blessing', models.CharField(blank=True, max_length=1000)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Lời Chúc',
            },
        ),
    ]
