# Generated by Django 2.2.1 on 2019-09-13 03:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mystory', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='about',
            options={'verbose_name_plural': 'Quản Lý Thông Tin CD-CR'},
        ),
        migrations.AlterModelOptions(
            name='gallery',
            options={'verbose_name_plural': 'Quản Lý Album'},
        ),
        migrations.AlterModelOptions(
            name='image',
            options={'verbose_name_plural': 'Quản Lý Hình Ảnh'},
        ),
        migrations.AlterModelOptions(
            name='invitee',
            options={'verbose_name_plural': 'Quản Lý Khách Mời'},
        ),
        migrations.AlterModelOptions(
            name='wedding_invitation',
            options={'verbose_name_plural': 'Quản Lý Thiệp Cưới'},
        ),
        migrations.AlterField(
            model_name='about',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='blessing',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='story',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
