# Generated by Django 2.2.5 on 2019-09-16 04:23

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mystory', '0002_auto_20190913_1025'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='avatar',
            field=models.ImageField(blank=True, upload_to='about', verbose_name='Ảnh Đại Diện'),
        ),
        migrations.AlterField(
            model_name='about',
            name='code',
            field=models.CharField(max_length=10, verbose_name='Mã code'),
        ),
        migrations.AlterField(
            model_name='about',
            name='ishusban',
            field=models.BooleanField(default=1, verbose_name='Là Chú Rể'),
        ),
        migrations.AlterField(
            model_name='about',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Họ Tên'),
        ),
        migrations.AlterField(
            model_name='blessing',
            name='blessing',
            field=models.CharField(blank=True, max_length=1000, verbose_name='Lời chúc'),
        ),
        migrations.AlterField(
            model_name='blessing',
            name='name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Tên khác mời'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='decription',
            field=models.CharField(blank=True, max_length=200, verbose_name='Nội dung'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Bộ sưu tập'),
        ),
        migrations.AlterField(
            model_name='image',
            name='decription',
            field=models.CharField(blank=True, max_length=50000, verbose_name='Ghi chú'),
        ),
        migrations.AlterField(
            model_name='image',
            name='gallery',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mystory.Gallery', verbose_name='Bộ sưu tập'),
        ),
        migrations.AlterField(
            model_name='image',
            name='path_img',
            field=models.ImageField(blank=True, upload_to='gallery/%Y/%m/%d', verbose_name='Đường dẫn'),
        ),
        migrations.AlterField(
            model_name='invitee',
            name='address',
            field=models.CharField(max_length=100, verbose_name='Địa chỉ'),
        ),
        migrations.AlterField(
            model_name='invitee',
            name='adherence_wedding',
            field=models.BooleanField(default=False, verbose_name='Đã Đến chung vui'),
        ),
        migrations.AlterField(
            model_name='invitee',
            name='guestof',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mystory.About', verbose_name='Khách của'),
        ),
        migrations.AlterField(
            model_name='invitee',
            name='ivitation',
            field=models.BooleanField(default=False, verbose_name='Đã phát thiệp'),
        ),
        migrations.AlterField(
            model_name='invitee',
            name='money_wedding',
            field=models.CharField(default=0, max_length=10, verbose_name='Tiền mừng'),
        ),
        migrations.AlterField(
            model_name='invitee',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Tên khách mời'),
        ),
        migrations.AlterField(
            model_name='invitee',
            name='phone',
            field=models.CharField(blank=True, max_length=13, validators=[django.core.validators.RegexValidator(message='Số điện thoại phải có định dạng 0xxxxxxxxxxx.', regex='^[0-9]{8,11}$')], verbose_name='Số điện thoại'),
        ),
        migrations.AlterField(
            model_name='story',
            name='content',
            field=models.CharField(blank=True, max_length=5000, verbose_name='Nội dung'),
        ),
        migrations.AlterField(
            model_name='story',
            name='images',
            field=models.ImageField(upload_to='story/%Y/%m/%d', verbose_name='Ảnh đại diện'),
        ),
        migrations.AlterField(
            model_name='story',
            name='title',
            field=models.CharField(blank=True, max_length=100, verbose_name='Tiêu đề'),
        ),
        migrations.AlterField(
            model_name='wedding_invitation',
            name='code',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='mystory.About', verbose_name='Tổ chức tại nhà'),
        ),
        migrations.AlterField(
            model_name='wedding_invitation',
            name='feast',
            field=models.CharField(choices=[('Vu Quy', 'Vu Quy'), ('Tân Hôn', 'Tân Hôn')], max_length=100, verbose_name='Lễ'),
        ),
        migrations.AlterField(
            model_name='wedding_invitation',
            name='location',
            field=models.CharField(max_length=500, verbose_name='Địa điểm tổ chức:'),
        ),
        migrations.AlterField(
            model_name='wedding_invitation',
            name='time_calendar',
            field=models.DateField(verbose_name='Ngày Dương Lịch'),
        ),
        migrations.AlterField(
            model_name='wedding_invitation',
            name='time_lunar',
            field=models.DateField(verbose_name='Ngày Âm Lịch'),
        ),
    ]
