# Generated by Django 2.1 on 2019-09-17 00:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mystory', '0003_auto_20190916_1123'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Tên Menu')),
                ('slug', models.SlugField(max_length=200)),
                ('link', models.CharField(max_length=100, verbose_name='Đường link')),
                ('background', models.ImageField(upload_to='menu/%Y/%m/%d', verbose_name='Ảnh Nền')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Quản Lý Menu',
                'verbose_name_plural': 'Quản Lý Menu',
            },
        ),
        migrations.AlterModelOptions(
            name='about',
            options={'verbose_name': 'Thông Tin', 'verbose_name_plural': 'Quản Lý Thông Tin CD-CR'},
        ),
        migrations.AlterModelOptions(
            name='blessing',
            options={'verbose_name': 'Lời Chúc', 'verbose_name_plural': 'Quản Lý Lời Chúc'},
        ),
        migrations.AlterModelOptions(
            name='gallery',
            options={'verbose_name': 'Khoảnh Khắc', 'verbose_name_plural': 'Quản Lý Album'},
        ),
        migrations.AlterModelOptions(
            name='image',
            options={'verbose_name': 'Hình Ảnh', 'verbose_name_plural': 'Quản Lý Hình Ảnh'},
        ),
        migrations.AlterModelOptions(
            name='invitee',
            options={'verbose_name': 'Khách Mời', 'verbose_name_plural': 'Quản Lý Khách Mời'},
        ),
        migrations.AlterModelOptions(
            name='story',
            options={'verbose_name': 'Nhật Ký', 'verbose_name_plural': 'Quản Lý Nhật Ký'},
        ),
        migrations.AlterModelOptions(
            name='wedding_invitation',
            options={'verbose_name': 'Thiệp Cưới', 'verbose_name_plural': 'Quản Lý Thiệp Cưới'},
        ),
        migrations.RenameField(
            model_name='about',
            old_name='avatar',
            new_name='image',
        ),
    ]
