# Generated by Django 2.1 on 2019-09-18 13:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mystory', '0004_auto_20190917_0711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Thêm bởi'),
        ),
        migrations.AlterField(
            model_name='blessing',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Thêm bởi'),
        ),
        migrations.AlterField(
            model_name='image',
            name='path_img',
            field=models.ImageField(blank=True, upload_to='gallery', verbose_name='Đường dẫn'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='background',
            field=models.ImageField(upload_to='menu', verbose_name='Ảnh Nền'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='link',
            field=models.CharField(choices=[('index', 'TRANG CHU'), ('about', 'THONG TIN'), ('story', 'NHAT KY'), ('invitation', 'TIEC CUOI'), ('gallery', 'KHOANH KHAC'), ('blessing', 'LOI CHUC')], max_length=100, verbose_name='Đường link'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='name',
            field=models.CharField(choices=[('index', 'TRANG CHU'), ('about', 'THONG TIN'), ('story', 'NHAT KY'), ('invitation', 'TIEC CUOI'), ('gallery', 'KHOANH KHAC'), ('blessing', 'LOI CHUC')], max_length=100, verbose_name='Tên MENU'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Thêm bởi'),
        ),
        migrations.AlterField(
            model_name='story',
            name='images',
            field=models.ImageField(upload_to='story', verbose_name='Ảnh đại diện'),
        ),
        migrations.AlterField(
            model_name='story',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Thêm bởi'),
        ),
    ]
