# Generated by Django 2.1 on 2019-09-18 14:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mystory', '0005_auto_20190918_2057'),
    ]

    operations = [
        migrations.CreateModel(
            name='Music',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Tên Bài Hát')),
                ('slug', models.SlugField(max_length=200)),
                ('link', models.CharField(max_length=100, verbose_name='Link Nhạc')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Quản Lý Nhạc Nền',
                'verbose_name_plural': 'Quản Lý Nhạc Nền',
            },
        ),
        migrations.RemoveField(
            model_name='menu',
            name='slug',
        ),
        migrations.AlterField(
            model_name='menu',
            name='link',
            field=models.SlugField(max_length=200),
        ),
        migrations.AlterField(
            model_name='menu',
            name='name',
            field=models.CharField(choices=[('TRANG CHỦ', 'TRANG CHỦ'), ('THôNG TIN', 'THôNG TIN'), ('NHẬT KÝ', 'NHẬT KÝ'), ('TIỆC CƯỚI', 'TIỆC CƯỚI'), ('KHOẢNH KHẮC', 'KHOẢNH KHẮC'), ('LỜI CHÚC', 'LỜI CHÚC')], max_length=100, verbose_name='Tên MENU'),
        ),
        migrations.AddField(
            model_name='music',
            name='menu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mystory.Menu', verbose_name='Phát Nhạc Ở'),
        ),
        migrations.AddField(
            model_name='music',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Thêm bởi'),
        ),
    ]
