# Generated by Django 2.1 on 2019-09-18 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mystory', '0006_auto_20190918_2152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='name',
            field=models.CharField(choices=[('TRANG CHỦ', 'TRANG CHỦ'), ('THÔNG TIN', 'THÔNG TIN'), ('NHẬT KÝ', 'NHẬT KÝ'), ('TIỆC CƯỚI', 'TIỆC CƯỚI'), ('KHOẢNH KHẮC', 'KHOẢNH KHẮC'), ('LỜI CHÚC', 'LỜI CHÚC')], max_length=100, verbose_name='Tên MENU'),
        ),
        migrations.AlterField(
            model_name='wedding_invitation',
            name='time_calendar',
            field=models.DateTimeField(verbose_name='Ngày Dương Lịch'),
        ),
        migrations.AlterField(
            model_name='wedding_invitation',
            name='time_lunar',
            field=models.DateTimeField(verbose_name='Ngày Âm Lịch'),
        ),
    ]
