# Generated by Django 2.1 on 2019-09-18 18:31

from django.db import migrations, models
import djrichtextfield.models


class Migration(migrations.Migration):

    dependencies = [
        ('mystory', '0007_auto_20190918_2311'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='decription',
            field=djrichtextfield.models.RichTextField(blank=True, null=True, verbose_name='Giới Thiệu Bản Thân'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='name',
            field=models.CharField(choices=[('TRANG CHỦ', 'TRANG CHỦ'), ('CÔ DÂU', 'CÔ DÂU'), ('CHÚ RỂ', 'CHÚ RỂ'), ('NHẬT KÝ', 'NHẬT KÝ'), ('TIỆC CƯỚI', 'TIỆC CƯỚI'), ('KHOẢNH KHẮC', 'KHOẢNH KHẮC'), ('LỜI CHÚC', 'LỜI CHÚC')], max_length=100, verbose_name='Tên MENU'),
        ),
    ]
