# Generated by Django 2.2.5 on 2019-09-19 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mystory', '0009_auto_20190919_0135'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='slide_show',
            field=models.BooleanField(default=1, verbose_name='Ảnh Trình Chiếu'),
        ),
        migrations.AddField(
            model_name='music',
            name='play_show',
            field=models.BooleanField(default=1, verbose_name='Nhạc Nền Slide Show'),
        ),
        migrations.AlterField(
            model_name='image',
            name='decription',
            field=models.CharField(blank=True, max_length=500, verbose_name='Ghi chú'),
        ),
    ]
