# Generated by Django 2.2.5 on 2019-09-19 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mystory', '0010_auto_20190919_1020'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='feeling',
            field=models.CharField(blank=True, max_length=100, verbose_name='Cảm Nhận'),
        ),
    ]
