# Generated by Django 2.2.5 on 2019-09-20 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mystory', '0013_auto_20190919_1640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='music',
            name='link',
            field=models.CharField(max_length=2000, verbose_name='Link Nhạc'),
        ),
    ]
