# Generated by Django 2.1 on 2019-09-21 04:14

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import djrichtextfield.models


class Migration(migrations.Migration):

    dependencies = [
        ('mystory', '0014_auto_20190920_1315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='code',
            field=models.CharField(default='', max_length=10, verbose_name='Mã code'),
        ),
        migrations.AlterField(
            model_name='about',
            name='decription',
            field=djrichtextfield.models.RichTextField(blank=True, default='', null=True, verbose_name='Giới Thiệu Bản Thân'),
        ),
        migrations.AlterField(
            model_name='about',
            name='image',
            field=models.ImageField(blank=True, default='', upload_to='about', verbose_name='Ảnh Đại Diện'),
        ),
        migrations.AlterField(
            model_name='about',
            name='name',
            field=models.CharField(default='', max_length=200, verbose_name='Họ Tên'),
        ),
        migrations.AlterField(
            model_name='about',
            name='user',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Thêm bởi'),
        ),
        migrations.AlterField(
            model_name='blessing',
            name='blessing',
            field=models.TextField(blank=True, default='', max_length=2000, verbose_name='Lời chúc'),
        ),
        migrations.AlterField(
            model_name='blessing',
            name='name',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Tên khác mời'),
        ),
        migrations.AlterField(
            model_name='blessing',
            name='relation',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='Mối quan hệ'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='decription',
            field=djrichtextfield.models.RichTextField(blank=True, default='', verbose_name='Nội dung'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='title',
            field=models.CharField(default='', max_length=200, verbose_name='Bộ sưu tập'),
        ),
        migrations.AlterField(
            model_name='image',
            name='decription',
            field=models.CharField(blank=True, default='', max_length=500, verbose_name='Ghi chú'),
        ),
        migrations.AlterField(
            model_name='image',
            name='gallery',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='mystory.Gallery', verbose_name='Bộ sưu tập'),
        ),
        migrations.AlterField(
            model_name='image',
            name='path_img',
            field=models.ImageField(blank=True, default='', upload_to='gallery', verbose_name='Đường dẫn'),
        ),
        migrations.AlterField(
            model_name='invitee',
            name='address',
            field=models.CharField(default='', max_length=100, verbose_name='Địa chỉ'),
        ),
        migrations.AlterField(
            model_name='invitee',
            name='guestof',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='mystory.About', verbose_name='Khách của'),
        ),
        migrations.AlterField(
            model_name='invitee',
            name='name',
            field=models.CharField(default='', max_length=100, verbose_name='Tên khách mời'),
        ),
        migrations.AlterField(
            model_name='invitee',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=13, validators=[django.core.validators.RegexValidator(message='Số điện thoại phải có định dạng 0xxxxxxxxxxx.', regex='^[0-9]{8,11}$')], verbose_name='Số điện thoại'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='background',
            field=models.ImageField(default='', upload_to='menu', verbose_name='Ảnh Nền'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='name',
            field=models.CharField(choices=[('TRANG CHỦ', 'TRANG CHỦ'), ('CÔ DÂU', 'CÔ DÂU'), ('CHÚ RỂ', 'CHÚ RỂ'), ('NHẬT KÝ', 'NHẬT KÝ'), ('TIỆC CƯỚI', 'TIỆC CƯỚI'), ('KHOẢNH KHẮC', 'KHOẢNH KHẮC'), ('LỜI CHÚC', 'LỜI CHÚC')], default='', max_length=100, verbose_name='Tên MENU'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Thêm bởi'),
        ),
        migrations.AlterField(
            model_name='music',
            name='link',
            field=models.CharField(default='', max_length=2000, verbose_name='Link Nhạc'),
        ),
        migrations.AlterField(
            model_name='music',
            name='name',
            field=models.CharField(default='', max_length=100, verbose_name='Tên Bài Hát'),
        ),
        migrations.AlterField(
            model_name='story',
            name='content',
            field=djrichtextfield.models.RichTextField(blank=True, default='', verbose_name='Nội dung'),
        ),
        migrations.AlterField(
            model_name='story',
            name='feeling',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Cảm Nhận'),
        ),
        migrations.AlterField(
            model_name='story',
            name='images',
            field=models.ImageField(default='', upload_to='story', verbose_name='Ảnh đại diện'),
        ),
        migrations.AlterField(
            model_name='story',
            name='title',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Tiêu đề'),
        ),
        migrations.AlterField(
            model_name='story',
            name='user',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Thêm bởi'),
        ),
        migrations.AlterField(
            model_name='wedding_invitation',
            name='code',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to='mystory.About', verbose_name='Tổ chức tại nhà'),
        ),
        migrations.AlterField(
            model_name='wedding_invitation',
            name='gmap',
            field=models.CharField(blank=True, default='', max_length=500, verbose_name='Google map'),
        ),
        migrations.AlterField(
            model_name='wedding_invitation',
            name='location',
            field=models.CharField(blank=True, default='', max_length=500, verbose_name='Địa điểm tổ chức'),
        ),
    ]
