# Generated by Django 2.1 on 2019-09-21 04:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mystory', '0015_auto_20190921_1114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wedding_invitation',
            name='time_calendar',
            field=models.DateTimeField(default=datetime.datetime(2019, 9, 21, 11, 15, 17, 863250), verbose_name='Ngày Dương Lịch'),
        ),
        migrations.AlterField(
            model_name='wedding_invitation',
            name='time_lunar',
            field=models.DateTimeField(default=datetime.datetime(2019, 9, 21, 11, 15, 17, 863250), verbose_name='Ngày Âm Lịch'),
        ),
    ]
